[package]
name = "rusty-backend"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.3.1"
async-std = "1.12.0"
pathfinding = "4.3.0"
rand = "0.8.5"
rusqlite = "0.29.0"
serde = "1.0.170"
serde_derive = "1.0.170"
serde_json = "1.0.100"
