[package]
name = "yas-backend"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "3.3.2"
async-std = "1.10.0"
rand = "0.8.4"
rusqlite = "0.26.1"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
