[package]
name = "yas-backend"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.0.1"
async-std = "1.11.0"
rand = "0.8.5"
rusqlite = "0.27.0"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
